package com.webSearch.docs;

import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.json.JsonMapper;
import com.webSearch.agent.dto.Architecture;
import com.webSearch.agent.dto.DatabaseDesign;
import com.webSearch.agent.dto.Diagrams;
import com.webSearch.agent.dto.EntityModel;
import com.webSearch.agent.dto.Lld;
import com.webSearch.agent.dto.Modules;
import com.webSearch.agent.dto.Requirements;
import com.webSearch.session.DesignSession;

import java.util.List;

/** Renders each Markdown document from a {@link DesignSession}'s artifacts (null-safe). */
public final class DocTemplates {

    private static final ObjectMapper MAPPER = JsonMapper.builder().build();
    private static final String NA = "_Not generated._\n";

    private DocTemplates() {
    }

    public static String readme(DesignSession s) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Architecture Design\n\n");
        sb.append("> Generated by the AI Software Architecture Copilot.\n\n");
        sb.append("## Idea\n\n").append(s.getIdea()).append("\n\n");
        Requirements req = s.getRequirements();
        if (req != null) {
            sb.append("## Requirements\n\n");
            sb.append("**Functional:**\n\n").append(bullets(req.functional())).append("\n");
            sb.append("**Non-functional:**\n\n").append(bullets(req.nonFunctional())).append("\n");
        }
        sb.append("## Documentation Index\n\n")
                .append("- [Architecture](architecture.md)\n")
                .append("- [High-Level Design](hld.md)\n")
                .append("- [Module Design](module-design.md)\n")
                .append("- [Entities](entities.md)\n")
                .append("- [Database](database.md)\n")
                .append("- [Low-Level Design](lld.md)\n")
                .append("- [API](api.md)\n")
                .append("- [Sequence Diagrams](sequence-diagrams.md)\n")
                .append("- [Class Diagrams](class-diagrams.md)\n")
                .append("- [Developer Guide](developer-guide.md)\n")
                .append("- [OpenAPI Spec](openapi.yaml)\n")
                .append("- Phase-wise Claude build prompts: `prompts/`\n")
                .append("- Raw diagram sources: `diagrams/`\n\n");
        if (!s.getAgentErrors().isEmpty()) {
            sb.append("## Generation Notes\n\nSome steps reported issues during generation:\n\n")
                    .append(bullets(s.getAgentErrors()));
        }
        return sb.toString();
    }

    public static String architecture(DesignSession s) {
        Architecture a = s.getArchitecture();
        if (a == null) {
            return "# Architecture\n\n" + NA;
        }
        StringBuilder sb = new StringBuilder("# Architecture\n\n");
        sb.append("**Style:** ").append(nz(a.style())).append("\n\n");
        sb.append("**Rationale:** ").append(nz(a.rationale())).append("\n\n");
        sb.append("## Layers\n\n");
        if (a.layers() != null) {
            for (Architecture.Layer layer : a.layers()) {
                sb.append("### ").append(nz(layer.name())).append("\n\n")
                        .append(nz(layer.responsibility())).append("\n\n")
                        .append(bullets(layer.components())).append("\n");
            }
        }
        sb.append("## Cross-Cutting Concerns\n\n").append(bullets(a.crossCuttingConcerns())).append("\n");
        return sb.toString();
    }

    public static String hld(DesignSession s) {
        Architecture a = s.getArchitecture();
        Modules m = s.getModules();
        StringBuilder sb = new StringBuilder("# High-Level Design\n\n");
        if (a != null) {
            sb.append("## Request Flow\n\n").append(numbered(a.requestFlow())).append("\n");
        }
        if (m != null && m.dependencies() != null) {
            sb.append("## Module Communication\n\n");
            for (Modules.Dependency d : m.dependencies()) {
                sb.append("- `").append(nz(d.from())).append("` → `").append(nz(d.to()))
                        .append("` (").append(nz(d.type())).append("): ").append(nz(d.reason())).append("\n");
            }
            sb.append("\n");
        }
        if (a == null && m == null) {
            sb.append(NA);
        }
        return sb.toString();
    }

    public static String lld(DesignSession s) {
        Lld l = s.getLld();
        if (l == null) {
            return "# Low-Level Design\n\n" + NA;
        }
        StringBuilder sb = new StringBuilder("# Low-Level Design\n\n");

        sb.append("## Package Structure\n\n");
        if (l.packages() != null) {
            for (Lld.PackageNode p : l.packages()) {
                sb.append("- `").append(nz(p.path())).append("` — ").append(nz(p.purpose())).append("\n");
            }
        }
        sb.append("\n## Services\n\n");
        if (l.services() != null) {
            for (Lld.ServiceSpec svc : l.services()) {
                sb.append("### ").append(nz(svc.iface()))
                        .append(" → ").append(nz(svc.impl())).append("\n\n");
                if (svc.methods() != null) {
                    for (Lld.ServiceSpec.MethodSpec mth : svc.methods()) {
                        sb.append("- `").append(nz(mth.signature())).append("` — ")
                                .append(nz(mth.behavior())).append("\n");
                    }
                }
                sb.append("\n");
            }
        }
        sb.append("## Controllers\n\n");
        if (l.controllers() != null) {
            for (Lld.ControllerSpec c : l.controllers()) {
                sb.append("### ").append(nz(c.name())).append(" (`").append(nz(c.basePath())).append("`)\n\n");
                if (c.endpoints() != null) {
                    for (Lld.ControllerSpec.Endpoint e : c.endpoints()) {
                        sb.append("- `").append(nz(e.httpMethod())).append(" ").append(nz(e.path()))
                                .append("` — ").append(nz(e.summary()))
                                .append(" _(req: ").append(nz(e.requestDto()))
                                .append(", res: ").append(nz(e.responseDto())).append(")_\n");
                    }
                }
                sb.append("\n");
            }
        }
        sb.append("## Exception Hierarchy\n\n");
        if (l.exceptions() != null) {
            sb.append("Base: `").append(nz(l.exceptions().base())).append("`\n\n");
            if (l.exceptions().types() != null) {
                for (Lld.ExceptionHierarchy.ExceptionType t : l.exceptions().types()) {
                    sb.append("- `").append(nz(t.name())).append("` extends `").append(nz(t.parent()))
                            .append("` → HTTP ").append(t.httpStatus()).append(" (").append(nz(t.when())).append(")\n");
                }
            }
        }
        sb.append("\n## Entities & DTOs\n\n```json\n")
                .append(json(new EntitiesAndDtos(l.entities(), l.dtos())))
                .append("\n```\n");
        return sb.toString();
    }

    public static String moduleDesign(DesignSession s) {
        Modules m = s.getModules();
        if (m == null) {
            return "# Module Design\n\n" + NA;
        }
        StringBuilder sb = new StringBuilder("# Module Design\n\n");
        if (m.modules() != null) {
            for (Modules.Module mod : m.modules()) {
                sb.append("## ").append(nz(mod.name())).append("\n\n")
                        .append("**Responsibility:** ").append(nz(mod.responsibility())).append("\n\n")
                        .append("**Capabilities:**\n\n").append(bullets(mod.capabilities())).append("\n");
            }
        }
        sb.append("## Dependencies\n\n");
        if (m.dependencies() != null) {
            for (Modules.Dependency d : m.dependencies()) {
                sb.append("- `").append(nz(d.from())).append("` → `").append(nz(d.to()))
                        .append("` (").append(nz(d.type())).append("): ").append(nz(d.reason())).append("\n");
            }
        }
        return sb.toString();
    }

    public static String database(DesignSession s) {
        DatabaseDesign d = s.getDatabase();
        if (d == null) {
            return "# Database\n\n" + NA;
        }
        StringBuilder sb = new StringBuilder("# Database\n\n");
        if (d.tables() != null) {
            for (DatabaseDesign.Table t : d.tables()) {
                sb.append("## ").append(nz(t.name())).append("\n\n");
                sb.append("| Column | Type | PK | Nullable | Note |\n|---|---|---|---|---|\n");
                if (t.columns() != null) {
                    for (DatabaseDesign.Table.Column c : t.columns()) {
                        sb.append("| ").append(nz(c.name())).append(" | ").append(nz(c.type()))
                                .append(" | ").append(c.primaryKey() ? "yes" : "")
                                .append(" | ").append(c.nullable() ? "yes" : "no")
                                .append(" | ").append(nz(c.note())).append(" |\n");
                    }
                }
                sb.append("\n");
                if (t.indexes() != null && !t.indexes().isEmpty()) {
                    sb.append("**Indexes:** ").append(String.join(", ", t.indexes())).append("\n\n");
                }
                if (t.constraints() != null && !t.constraints().isEmpty()) {
                    sb.append("**Constraints:** ").append(String.join(", ", t.constraints())).append("\n\n");
                }
            }
        }
        if (d.relationships() != null && !d.relationships().isEmpty()) {
            sb.append("## Relationships\n\n");
            for (DatabaseDesign.Relationship r : d.relationships()) {
                sb.append("- `").append(nz(r.from())).append("` — `").append(nz(r.to()))
                        .append("` (").append(nz(r.cardinality())).append(", onDelete=")
                        .append(nz(r.onDelete())).append(")\n");
            }
            sb.append("\n");
        }
        sb.append("## Rationale\n\n").append(nz(d.rationale())).append("\n\n");
        if (d.erMermaid() != null && !d.erMermaid().isBlank()) {
            sb.append("## ER Diagram\n\n```mermaid\n").append(d.erMermaid().strip()).append("\n```\n");
        }
        return sb.toString();
    }

    public static String api(DesignSession s) {
        Lld l = s.getLld();
        if (l == null || l.controllers() == null) {
            return "# API\n\n" + NA;
        }
        StringBuilder sb = new StringBuilder("# API\n\n");
        for (Lld.ControllerSpec c : l.controllers()) {
            sb.append("## ").append(nz(c.name())).append("\n\nBase path: `").append(nz(c.basePath())).append("`\n\n");
            if (c.endpoints() != null) {
                for (Lld.ControllerSpec.Endpoint e : c.endpoints()) {
                    sb.append("### ").append(nz(e.httpMethod())).append(" ").append(nz(e.path())).append("\n\n")
                            .append(nz(e.summary())).append("\n\n")
                            .append("- Request: `").append(nz(e.requestDto())).append("`\n")
                            .append("- Response: `").append(nz(e.responseDto())).append("`\n\n");
                }
            }
        }
        return sb.toString();
    }

    public static String entities(DesignSession s) {
        EntityModel m = s.getEntities();
        if (m == null) {
            return "# Entities\n\n" + NA;
        }
        StringBuilder sb = new StringBuilder("# Entities (Domain Model)\n\n");
        if (m.entities() != null) {
            for (EntityModel.Entity e : m.entities()) {
                sb.append("## ").append(nz(e.name()));
                if (e.module() != null && !e.module().isBlank()) {
                    sb.append(" _(").append(e.module()).append(")_");
                }
                sb.append("\n\n").append(nz(e.description())).append("\n\n");
                sb.append("| Attribute | Type | Id | Required | Note |\n|---|---|---|---|---|\n");
                if (e.attributes() != null) {
                    for (EntityModel.Entity.Attribute a : e.attributes()) {
                        sb.append("| ").append(nz(a.name())).append(" | ").append(nz(a.type()))
                                .append(" | ").append(a.identifier() ? "yes" : "")
                                .append(" | ").append(a.required() ? "yes" : "no")
                                .append(" | ").append(nz(a.note())).append(" |\n");
                    }
                }
                sb.append("\n");
            }
        }
        if (m.relationships() != null && !m.relationships().isEmpty()) {
            sb.append("## Relationships\n\n");
            for (EntityModel.EntityRelationship r : m.relationships()) {
                sb.append("- `").append(nz(r.from())).append("` → `").append(nz(r.to()))
                        .append("` (").append(nz(r.cardinality())).append("): ")
                        .append(nz(r.description())).append("\n");
            }
            sb.append("\n");
        }
        sb.append("## Rationale\n\n").append(nz(m.rationale())).append("\n");
        return sb.toString();
    }

    public static String sequenceDiagrams(DesignSession s) {
        Diagrams d = s.getDiagrams();
        StringBuilder sb = new StringBuilder("# Sequence & Request-Flow Diagrams\n\n");
        appendDiagram(sb, "Sequence", d == null ? null : d.sequence());
        appendDiagram(sb, "Request Flow", d == null ? null : d.requestFlow());
        return sb.length() == "# Sequence & Request-Flow Diagrams\n\n".length() ? sb.append(NA).toString() : sb.toString();
    }

    public static String classDiagrams(DesignSession s) {
        Diagrams d = s.getDiagrams();
        StringBuilder sb = new StringBuilder("# Class & Component Diagrams\n\n");
        appendDiagram(sb, "Class Diagram", d == null ? null : d.classDiagram());
        appendDiagram(sb, "Component Diagram", d == null ? null : d.component());
        return sb.length() == "# Class & Component Diagrams\n\n".length() ? sb.append(NA).toString() : sb.toString();
    }

    public static String developerGuide(DesignSession s) {
        Lld l = s.getLld();
        Modules m = s.getModules();
        StringBuilder sb = new StringBuilder("# Developer Guide\n\n");
        sb.append("## Modules\n\n");
        if (m != null && m.modules() != null) {
            for (Modules.Module mod : m.modules()) {
                sb.append("- **").append(nz(mod.name())).append("** — ").append(nz(mod.responsibility())).append("\n");
            }
            sb.append("\n");
        }
        sb.append("## Package Layout\n\n");
        if (l != null && l.packages() != null) {
            for (Lld.PackageNode p : l.packages()) {
                sb.append("- `").append(nz(p.path())).append("` — ").append(nz(p.purpose())).append("\n");
            }
        }
        sb.append("\n## Build Prompts\n\n")
                .append("See the `prompts/` folder for the ordered, phase-wise Claude build prompts.\n");
        return sb.toString();
    }

    // --- helpers ---

    private record EntitiesAndDtos(List<Lld.JavaType> entities, List<Lld.JavaType> dtos) {
    }

    private static void appendDiagram(StringBuilder sb, String title, Diagrams.Diagram diagram) {
        if (diagram == null) {
            return;
        }
        if (diagram.mermaid() != null && !diagram.mermaid().isBlank()) {
            sb.append("## ").append(title).append(" (Mermaid)\n\n```mermaid\n")
                    .append(diagram.mermaid().strip()).append("\n```\n\n");
        }
        if (diagram.plantUml() != null && !diagram.plantUml().isBlank()) {
            sb.append("## ").append(title).append(" (PlantUML)\n\n```plantuml\n")
                    .append(diagram.plantUml().strip()).append("\n```\n\n");
        }
    }

    private static String bullets(List<String> items) {
        if (items == null || items.isEmpty()) {
            return "_None._\n";
        }
        StringBuilder sb = new StringBuilder();
        for (String i : items) {
            sb.append("- ").append(i).append("\n");
        }
        return sb.toString();
    }

    private static String numbered(List<String> items) {
        if (items == null || items.isEmpty()) {
            return "_None._\n";
        }
        StringBuilder sb = new StringBuilder();
        int n = 1;
        for (String i : items) {
            sb.append(n++).append(". ").append(i).append("\n");
        }
        return sb.toString();
    }

    private static String joinOrNone(List<String> items) {
        return (items == null || items.isEmpty()) ? "none" : String.join("; ", items);
    }

    private static String nz(String s) {
        return s == null ? "" : s;
    }

    private static String json(Object o) {
        try {
            return MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(o);
        } catch (Exception e) {
            return String.valueOf(o);
        }
    }
}
